version: '3.6'
services:
  app:
    build: .
    ports:
      - 4200:4200
      - 7020:7020
      - 7357:7357
      - 9222:9222
    volumes:
      - .:/project:cached
      - /project/dist
      - /project/electron-out
      - /project/node_modules
      - type: tmpfs
        target: /project/tmp
    env_file: .env
